version: '3.7'

networks:
  postgres:
    driver: bridge
  
services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'production'
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data


volumes:
  database-pg: